version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
    - MYSQL_DATABASE=capstone
    - MUSQL_USER=root
    - MYSQL_PASSWORD=garage2
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - mysql-db:/var/lib/mysql

  webapp:
    container_name: webapp
    build: ./Capstone-Web
    depends_on:
    - mysql
    ports:
    - "8080:8080"
    environment:
    - DATABASE_HOST=mysql
    - DATABASE_NAME=capstone
    - DATABASE_USER=root
    - DATABASE_PASSWORD=garage2
    - DATABASE_PORT=3306

#  notificationApp:
#    container_name: notification-app
#    build: ./Capstone-Email
#    depends_on:
#      - webapp
#    ports:
#      - "8081:8081"

volumes:
  mysql-db: