version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
    - MYSQL_DATABASE=capstone
    - MUSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - mysql-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 60s
      retries: 5

  webapp:
    container_name: webapp
    build: ./Capstone-Web
    depends_on:
    - mysql
    - eukeka-server
    ports:
    - "8082:8082"
    environment:
    - DATABASE_HOST=mysql
    - DATABASE_NAME=capstone
    - DATABASE_USER=root
    - DATABASE_PASSWORD=root
    - DATABASE_PORT=3306
    healthcheck:
      test: curl -sS http://127.0.0.1 || echo 1
      interval: 5s
      timeout: 10s
      retries: 3

  notification-app:
    container_name: notification-app
    build: ./Capstone-Email
    depends_on:
      - webapp
      - eukeka-server
    ports:
      - "8081:8081"
    healthcheck:
      test: curl -sS http://127.0.0.1 || echo 1
      interval: 5s
      timeout: 10s
      retries: 3

  zuul:
    container_name: zuul
    build: ./Capstone-Zuul
    depends_on:
    - eukeka-server
    ports:
      - "8080:8080"


  eukeka-server:
    container_name: eureka-server
    build: ./Capstone-Eureka-Server
    ports:
      - "8761:8761"

volumes:
  mysql-db: