spring:
  application:
    name: webapp
  datasource:
    url: jdbc:mysql://mysql:3306/capstone?serverTimezone=UTC
    username: root
    password: garage2
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        use-new-id-generator-mappings: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
          #                  id:
          #                    new_generator_mappings: false
          #          TODO what is it

security:
  jwt:
    token:
      secret-key: secret-key
      #      TODO change
      expire-length: 3600000 #1 hour

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
server:
  port: 8082

services:
  email: http://notification-app:8081/notification

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8061/eureka/