spring:
  application:
    name: notification-app
server:
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

  client:
    serviceUrl:
      #      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/
